// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpeechServiceClient is the client API for SpeechService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpeechServiceClient interface {
	SpeechToText(ctx context.Context, in *SpeechToTextRequest, opts ...grpc.CallOption) (*SpeechToTextResponse, error)
}

type speechServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeechServiceClient(cc grpc.ClientConnInterface) SpeechServiceClient {
	return &speechServiceClient{cc}
}

func (c *speechServiceClient) SpeechToText(ctx context.Context, in *SpeechToTextRequest, opts ...grpc.CallOption) (*SpeechToTextResponse, error) {
	out := new(SpeechToTextResponse)
	err := c.cc.Invoke(ctx, "/SpeechService/SpeechToText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpeechServiceServer is the server API for SpeechService service.
// All implementations must embed UnimplementedSpeechServiceServer
// for forward compatibility
type SpeechServiceServer interface {
	SpeechToText(context.Context, *SpeechToTextRequest) (*SpeechToTextResponse, error)
	mustEmbedUnimplementedSpeechServiceServer()
}

// UnimplementedSpeechServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSpeechServiceServer struct {
}

func (UnimplementedSpeechServiceServer) SpeechToText(context.Context, *SpeechToTextRequest) (*SpeechToTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpeechToText not implemented")
}
func (UnimplementedSpeechServiceServer) mustEmbedUnimplementedSpeechServiceServer() {}

// UnsafeSpeechServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeechServiceServer will
// result in compilation errors.
type UnsafeSpeechServiceServer interface {
	mustEmbedUnimplementedSpeechServiceServer()
}

func RegisterSpeechServiceServer(s grpc.ServiceRegistrar, srv SpeechServiceServer) {
	s.RegisterService(&SpeechService_ServiceDesc, srv)
}

func _SpeechService_SpeechToText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpeechToTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeechServiceServer).SpeechToText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpeechService/SpeechToText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeechServiceServer).SpeechToText(ctx, req.(*SpeechToTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpeechService_ServiceDesc is the grpc.ServiceDesc for SpeechService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeechService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SpeechService",
	HandlerType: (*SpeechServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpeechToText",
			Handler:    _SpeechService_SpeechToText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "speech.proto",
}
