version: "3.9"

networks:
  infra-vlan:


volumes:
  postgres-data:
  redis-data:
  whisper-models:


services:
  app:
    build:
      context: "../backend/"
      dockerfile: "Dockerfile"
    restart: "no"
    command: "./main --docker=true"
    volumes:
      - ../config.yaml:/app/config.yaml
    env_file:
      - "../.env"
    ports:
      - "9999:9999"
      - "9000:9000"
      - "9991:9991"
    environment:
      - "POSTGRES_HOST=postgres"
    depends_on:
      - postgres
      - redis

    networks:
      - infra-vlan
      - default

  speech-to-text:
    build:
      context: "../speech-to-text/"
      dockerfile: "Dockerfile"
    command: python3 main.py
    ports:
      - "10000:10000"
    volumes:
      -  whisper-models:/root/.cache/whisper/
    networks:
      - default
      - infra-vlan
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5775:5775"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "4317:4317"
      - "4318:4318"
    networks:
      - infra-vlan
      - default

  prometheus:
    image: prom/prometheus:v2.28.0
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    networks:
      - infra-vlan


  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - infra-vlan
      - default


  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - infra-vlan

  postgres:
    image: "postgres:16"
    container_name: "database"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    env_file:
      - "../.env"
    ports:
      - "5432:5432"
    networks:
      - infra-vlan
      - default

  redis:
    image: 'redis:7.2.4'
    container_name: 'cache'
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/root/redis'
