# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cspeech.proto\"$\n\x13SpeechToTextRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"$\n\x14SpeechToTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2L\n\rSpeechService\x12;\n\x0cSpeechToText\x12\x14.SpeechToTextRequest\x1a\x15.SpeechToTextResponseB Z\x1e./internal/grpcserver/pb/orderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036./internal/grpcserver/pb/order'
  _globals['_SPEECHTOTEXTREQUEST']._serialized_start=16
  _globals['_SPEECHTOTEXTREQUEST']._serialized_end=52
  _globals['_SPEECHTOTEXTRESPONSE']._serialized_start=54
  _globals['_SPEECHTOTEXTRESPONSE']._serialized_end=90
  _globals['_SPEECHSERVICE']._serialized_start=92
  _globals['_SPEECHSERVICE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
