global:
  scrape_interval: 5s
  external_labels:
    monitor: 'monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'go-rest'
    static_configs:
      - targets: ['app:9991']

  - job_name: 'domain-detection-1'
    static_configs:
      - targets: ['domain-1:9991']

#  - job_name: 'domain-detection-2'
#    static_configs:
#      - targets: [ 'domain-2:9991']
