# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: preprocessor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12preprocessor.proto\"!\n\x11ProcessingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x12ProcessingResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2O\n\x15TextProcessingService\x12\x36\n\x0bProcessText\x12\x12.ProcessingRequest\x1a\x13.ProcessingResponseB\x07Z\x05./;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'preprocessor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./;pb'
  _globals['_PROCESSINGREQUEST']._serialized_start=22
  _globals['_PROCESSINGREQUEST']._serialized_end=55
  _globals['_PROCESSINGRESPONSE']._serialized_start=57
  _globals['_PROCESSINGRESPONSE']._serialized_end=91
  _globals['_TEXTPROCESSINGSERVICE']._serialized_start=93
  _globals['_TEXTPROCESSINGSERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
