# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: domain.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64omain.proto\"\'\n\x16\x44omainDetectionRequest\x12\r\n\x05query\x18\x01 \x01(\t\"(\n\x17\x44omainDetectionResponse\x12\r\n\x05label\x18\x01 \x01(\t2[\n\x16\x44omainDetectionService\x12\x41\n\x0c\x44\x65tectDomain\x12\x17.DomainDetectionRequest\x1a\x18.DomainDetectionResponseB\x07Z\x05./;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'domain_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./;pb'
  _globals['_DOMAINDETECTIONREQUEST']._serialized_start=16
  _globals['_DOMAINDETECTIONREQUEST']._serialized_end=55
  _globals['_DOMAINDETECTIONRESPONSE']._serialized_start=57
  _globals['_DOMAINDETECTIONRESPONSE']._serialized_end=97
  _globals['_DOMAINDETECTIONSERVICE']._serialized_start=99
  _globals['_DOMAINDETECTIONSERVICE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
