# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import domain_pb2 as domain__pb2


class DomainDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectDomain = channel.unary_unary(
                '/DomainDetectionService/DetectDomain',
                request_serializer=domain__pb2.DomainDetectionRequest.SerializeToString,
                response_deserializer=domain__pb2.DomainDetectionResponse.FromString,
                )


class DomainDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectDomain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DomainDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectDomain,
                    request_deserializer=domain__pb2.DomainDetectionRequest.FromString,
                    response_serializer=domain__pb2.DomainDetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DomainDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DomainDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DomainDetectionService/DetectDomain',
            domain__pb2.DomainDetectionRequest.SerializeToString,
            domain__pb2.DomainDetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
